language: php

php:
  - 7.3
  - 7.4snapshot

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
  allow_failures:
    - php: 7.4snapshot
    
install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-text  --coverage-clover=coverage.clover
